[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

remappings = [
    "n-per-epoch/=lib/n-per-epoch/src",
    "worldcoin/world-id/=lib/n-per-epoch/lib/world-id-example-airdrop/src",
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
